# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: darshankrishna2k2@gmail.com
author_name: DarshanKrishna-DK
preset_name: starter
project_name: CitadelX-frontend

